[logger]
level = "INFO"
log_encoding = "console"

[database]
connect_str = "postgres://otus:otus@pg:5432/calendar"
storage = "sql"

[http-server]
address = "0.0.0.0:8081"

[grpc-server]
address = "0.0.0.0:5051"

