// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: EventService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	TimeBefore    *durationpb.Duration   `protobuf:"bytes,5,opt,name=TimeBefore,proto3" json:"TimeBefore,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	UserID        string                 `protobuf:"bytes,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Event) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Event) GetTimeBefore() *durationpb.Duration {
	if x != nil {
		return x.TimeBefore
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         []*Event               `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *Events) GetEvent() []*Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RequestUuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUuid) Reset() {
	*x = RequestUuid{}
	mi := &file_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUuid) ProtoMessage() {}

func (x *RequestUuid) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUuid.ProtoReflect.Descriptor instead.
func (*RequestUuid) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUuid) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RequestDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDate) Reset() {
	*x = RequestDate{}
	mi := &file_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDate) ProtoMessage() {}

func (x *RequestDate) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDate.ProtoReflect.Descriptor instead.
func (*RequestDate) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{4}
}

func (x *RequestDate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_EventService_proto protoreflect.FileDescriptor

const file_EventService_proto_rawDesc = "" +
	"\n" +
	"\x12EventService.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x91\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x126\n" +
	"\bDateTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bDateTime\x125\n" +
	"\bDuration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bDuration\x129\n" +
	"\n" +
	"TimeBefore\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"TimeBefore\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\x12\x16\n" +
	"\x06UserID\x18\a \x01(\tR\x06UserID\",\n" +
	"\x06Events\x12\"\n" +
	"\x05event\x18\x01 \x03(\v2\f.event.EventR\x05event\"\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"!\n" +
	"\vRequestUuid\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"!\n" +
	"\vRequestDate\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date2\xab\x02\n" +
	"\tEventsApi\x12)\n" +
	"\x06Create\x12\f.event.Event\x1a\x0f.event.Response\"\x00\x12)\n" +
	"\x06Update\x12\f.event.Event\x1a\x0f.event.Response\"\x00\x12/\n" +
	"\x06Delete\x12\x12.event.RequestUuid\x1a\x0f.event.Response\"\x00\x120\n" +
	"\tListOnDay\x12\x12.event.RequestDate\x1a\r.event.Events\"\x00\x121\n" +
	"\n" +
	"ListOnWeek\x12\x12.event.RequestDate\x1a\r.event.Events\"\x00\x122\n" +
	"\vListOnMonth\x12\x12.event.RequestDate\x1a\r.event.Events\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_EventService_proto_rawDescOnce sync.Once
	file_EventService_proto_rawDescData []byte
)

func file_EventService_proto_rawDescGZIP() []byte {
	file_EventService_proto_rawDescOnce.Do(func() {
		file_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EventService_proto_rawDesc), len(file_EventService_proto_rawDesc)))
	})
	return file_EventService_proto_rawDescData
}

var file_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_EventService_proto_goTypes = []any{
	(*Event)(nil),                 // 0: event.Event
	(*Events)(nil),                // 1: event.Events
	(*Response)(nil),              // 2: event.Response
	(*RequestUuid)(nil),           // 3: event.RequestUuid
	(*RequestDate)(nil),           // 4: event.RequestDate
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 6: google.protobuf.Duration
}
var file_EventService_proto_depIdxs = []int32{
	5,  // 0: event.Event.DateTime:type_name -> google.protobuf.Timestamp
	6,  // 1: event.Event.Duration:type_name -> google.protobuf.Duration
	6,  // 2: event.Event.TimeBefore:type_name -> google.protobuf.Duration
	0,  // 3: event.Events.event:type_name -> event.Event
	0,  // 4: event.EventsApi.Create:input_type -> event.Event
	0,  // 5: event.EventsApi.Update:input_type -> event.Event
	3,  // 6: event.EventsApi.Delete:input_type -> event.RequestUuid
	4,  // 7: event.EventsApi.ListOnDay:input_type -> event.RequestDate
	4,  // 8: event.EventsApi.ListOnWeek:input_type -> event.RequestDate
	4,  // 9: event.EventsApi.ListOnMonth:input_type -> event.RequestDate
	2,  // 10: event.EventsApi.Create:output_type -> event.Response
	2,  // 11: event.EventsApi.Update:output_type -> event.Response
	2,  // 12: event.EventsApi.Delete:output_type -> event.Response
	1,  // 13: event.EventsApi.ListOnDay:output_type -> event.Events
	1,  // 14: event.EventsApi.ListOnWeek:output_type -> event.Events
	1,  // 15: event.EventsApi.ListOnMonth:output_type -> event.Events
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_EventService_proto_init() }
func file_EventService_proto_init() {
	if File_EventService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EventService_proto_rawDesc), len(file_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EventService_proto_goTypes,
		DependencyIndexes: file_EventService_proto_depIdxs,
		MessageInfos:      file_EventService_proto_msgTypes,
	}.Build()
	File_EventService_proto = out.File
	file_EventService_proto_goTypes = nil
	file_EventService_proto_depIdxs = nil
}
